language: generic
sudo: requires
services:
  - docker
before_install:
  - docker build -t clarags/react-test -f ./client/Dockerfile.dev ./client
  # here i could add more test suits, in case i wanted to also test the api etc
script:
  - docker run -e CI=true clarags/react-test npm test
  # here I could add more cmds to run
after_success:
  - docker build -t clarags/multi-client ./client 
  - docker build -t clarags/multi-nginx ./nginx 
  - docker build -t clarags/multi-server ./server 
  - docker build -t clarags/multi-worker ./worker 
  # Log in into docker CLI
  - echo "$DOCKER_PSW" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push clarags/multi-client
  - docker push clarags/multi-nginx
  - docker push clarags/multi-server
  - docker push clarags/multi-worker
deploy:
  provider: elastickbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucker_name: "elasticbeanstalk-eu-west-2-452355874645"
  bucker_path: "multi-docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
